# Generated by Django 4.1.3 on 2023-08-02 21:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile name', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=6, message='Username is too short, add at least %(limit_value)d characters'), django.core.validators.MaxLengthValidator(limit_value=15, message='Username is too long, the limit is %(limit_value)dthe you provide has %(show_value)d characters')])),
                ('sing_up_date', models.DateField(default=django.utils.timezone.now)),
                ('profile_pic', models.ImageField(upload_to='images')),
            ],
        ),
    ]
