# Generated by Django 4.1.3 on 2023-08-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile name',
            new_name='name',
        ),
    ]
