metal_subgenres = [
    "Heavy Metal",
    "Thrash Metal",
    "Death Metal",
    "Black Metal",
    "Power Metal",
    "Doom Metal",
    "Progressive Metal",
    "Folk Metal",
    "Symphonic Metal",
    "Industrial Metal",
    "Groove Metal",
    "Nu Metal",
    "Metalcore",
    "Deathcore",
    "Melodic Death Metal",
    "Technical Death Metal",
    "Atmospheric Black Metal",
    "Viking Metal",
    "Gothic Metal",
    "Sludge Metal",
    "Stoner Metal",
    "Post-Metal",
    "Speed Metal",
    "Glam Metal",
    "Djent",
    "Mathcore",
    "Avant-Garde Metal",
    "Neoclassical Metal",
    "Grindcore",
    "Cyber Metal",
    "Folk Black Metal",
    "Alternative Metal",
    "Crossover Thrash",
    "Progressive Death Metal",
    "Post-Black Metal",
    "Depressive Suicidal Black Metal",
    "Pagan Metal",
    "Symphonic Black Metal",
    "Thrashcore",
    "Dark Metal",
    "Technical Thrash Metal",
    "Traditional Doom Metal",
    "Gothic Doom Metal",
    "Funeral Doom Metal",
    "Sludgecore"
]
