# Generated by Django 4.1.3 on 2023-07-27 21:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=25)),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('fundation_date', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1950, message='No artist before 1950'), django.core.validators.MaxValueValidator(limit_value=2023, message="Can't enter a higher than the current year")])),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('released_date', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='app_management.artist')),
            ],
        ),
    ]
