# Generated by Django 4.1.3 on 2023-07-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
