# Generated by Django 4.1.3 on 2023-08-01 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0002_alter_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
