# Generated by Django 4.1.3 on 2023-08-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0003_album_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
