# Generated by Django 4.1.3 on 2023-08-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0004_artist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='subgenres',
            field=models.JSONField(null=True),
        ),
    ]
