# Generated by Django 4.1.3 on 2023-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0006_alter_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
